# Generated by Django 6.0.1 on 2026-01-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_first_login",
            field=models.BooleanField(default=True, verbose_name="是否首次登入"),
        ),
    ]
