# Generated by Django 6.0.1 on 2026-01-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_first_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="最後登入IP"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_logout",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最後登入時間"
            ),
        ),
    ]
