# Generated by Django 6.0.1 on 2026-01-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_last_login_ip_user_last_logout"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(
                        upload_to="temp_imports/", verbose_name="CSV 檔案"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上傳時間"),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="已處理"),
                ),
                ("log_message", models.TextField(blank=True, verbose_name="處理紀錄")),
            ],
            options={
                "verbose_name": "學生名單匯入",
                "verbose_name_plural": "學生名單匯入",
            },
        ),
    ]
