# Generated by Django 6.0.1 on 2026-01-16 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_slot", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "已預約"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="預約事由"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="預約學生",
                    ),
                ),
            ],
            options={
                "verbose_name": "預約紀錄",
                "verbose_name_plural": "預約紀錄表",
                "ordering": ["-date", "time_slot"],
                "unique_together": {("date", "time_slot")},
            },
        ),
    ]
