# Generated by Django 6.0.1 on 2026-01-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "可預約"),
                    ("scheduled", "已預約"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
