# Generated by Django 6.0.1 on 2026-01-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True, verbose_name="拒絕預約理由"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "可預約"),
                    ("scheduled", "已預約"),
                    ("confirmed", "已確認"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
